### ISSUE TITLE
[usage question] How to get `block`, `filters` and `transaction` from the `client`? 

### ISSUE THREAD

**Issue by rajarshimaitra** [cloudhead/nakamoto#88]
I am currently trying to use nakamoto client to create a CBF backend for BDK. I am looking for ways to get the following stuffs from the client.. 

 - Given a `BlockHash`, get the full `Block`. There is a method `get_block()` but its not returning anything. So how can I get the block result after sending the command to the client?
 https://github.com/cloudhead/nakamoto/blob/66d0507896a4864dda3c4b0d08e30ef94c8d7a19/client/src/client.rs#L486-L490
 
 - Given a range get some filter: Same question for Filters. `gert_filters()` doesn't return anything. How can I get the filters?
 https://github.com/cloudhead/nakamoto/blob/66d0507896a4864dda3c4b0d08e30ef94c8d7a19/client/src/client.rs#L492-L501

-  Given a txid, get the transaction. IIUC the node contains all the confirmed and unconfirmed transactions in the Inventory manager. https://github.com/cloudhead/nakamoto/blob/66d0507896a4864dda3c4b0d08e30ef94c8d7a19/client/src/client.rs#L492-L501 . Is it possible to expose a `Handle` api to get one of those transaction given a txid?   

Thanks in advanced.. :)

**Comment by cloudhead** [comment]
> I am currently trying to use nakamoto client to create a CBF backend for BDK. I am looking for ways to get the following stuffs from the client..

Great!

> Given a BlockHash, get the full Block. There is a method get_block() but its not returning anything. So how can I get the block result after sending the command to the client?

All received and processed blocks will be sent over the events queue. You can listen for blocks specifically by calling `handle.blocks()`, which returns a channel you can iterate on, after you've requested a block be fetched via `handle.get_block()`. Note that this will only emit blocks once they have been processed *in order*, which only matters if you requested more than one block at a time.

> Given a range get some filter: Same question for Filters. gert_filters() doesn't return anything. How can I get the filters?

Same story, you can use `handle.filters()`. To wait on multiple channels, use `crossbeam_channel::select!` (https://docs.rs/crossbeam/latest/crossbeam/macro.select.html)

> Given a txid, get the transaction. IIUC the node contains all the confirmed and unconfirmed transactions in the Inventory manager. 

There's no code to fetch transactions from the network. The reason it's not implemented is that there isn't an obvious use for it when you have block filters, since you usually fetch full blocks that match, and those contain the txs. If you need this though, happy to help you add it. If you're asking about getting a tx that is in the client's mempool: this can be done, but it's only *unconfirmed* transactions. Confirmed transactions will be in the blocks themselves.

---

In case you haven't seen, there's also a way to scan the chain which automates the process of fetching filters and matching blocks: `handle.rescan()`. You can see an example of it used in `wallet/src/lib.rs`.

**Comment by rajarshimaitra** [comment]
> All received and processed blocks will be sent over the events queue. You can listen for blocks specifically by calling handle.blocks(), which returns a channel you can iterate on, after you've requested a block be fetched via handle.get_block(). Note that this will only emit blocks once they have been processed in order, which only matters if you requested more than one block at a time.

Thanks a lot.. This clears it up.. At the wallet level, the wallet isn't always concerned with blocks and filters.. Just a generic question I had on how to handle them as they weren't returning.. 

>  If you're asking about getting a tx that is in the client's mempool: this can be done, but it's only unconfirmed transactions. Confirmed transactions will be in the blocks themselves.

I am getting confirmed transactions alright via `Event::BlockMatched`. But I do need some ways to get the *unconfirmed* ones too. Stuffs in mempool.

I have been trying listen for `Event::TxStatusChanged` but they don't seem to be firing for both confirmed and unconfirmed transactions, not broadcasted via the client (Probably they are intended only for those that the client broadcast?).. 

The transaction I am looking for will be a "wallet related" transaction, broadcasted by someone else in the network, and the wallet needs to know when its reached the nakamoto client's mempool.. And the wallet will need to know the fell raw transaction, not just the Txid..

Any suggestion on this would be very helpful..

**Comment by cloudhead** [comment]
> The transaction I am looking for will be a "wallet related" transaction, broadcasted by someone else in the network, and the wallet needs to know when its reached the nakamoto client's mempool.. And the wallet will need to know the full raw transaction, not just the Txid..

Ah, this is tricky, but possible. The reason this isn't enabled though is that it would require listening for *all* transactions, ie. setting the client in "relay" mode. This is really expensive in terms of bandwidth, as you will be receiving inventory announcements all the time, like a full node. If you want to try this out though, you can modify the code here: https://github.com/cloudhead/nakamoto/blob/66d0507896a4864dda3c4b0d08e30ef94c8d7a19/p2p/src/protocol/peermgr.rs to `true`.

> I have been trying listen for Event::TxStatusChanged but they don't seem to be firing for both confirmed and unconfirmed transactions, not broadcasted via the client (Probably they are intended only for those that the client broadcast?)..

Yes, due to the above, we only know about txs not broadcast by the client when they end up in blocks. Unfortunately there's no reliable solution for light clients to track unconfirmed txs in a bandwidth-efficient way. I think most wallets use a service provider for this, since it's not a critical function (ie. it's ok to be wrong about it).

**Comment by rajarshimaitra** [comment]
> This is really expensive in terms of bandwidth, as you will be receiving inventory announcements all the time, like a full node. If you want to try this out though, you can modify the code here: https://github.com/cloudhead/nakamoto/blob/66d0507896a4864dda3c4b0d08e30ef94c8d7a19/p2p/src/protocol/peermgr.rs to true.

I guess I will try this route and see what happens.. Can you point to the config flag though to make the client relay? The link directs to the `peermngr` module and I couldn't find any suitable flag in the config..

Yes this thing sucks for light clients in general.. Is there any benchmark for this in mainnet with nakamoto? If not we might try it out with BDK and find out.. 

> Yes, due to the above, we only know about txs not broadcast by the client when they end up in blocks.

If I make the client in relay mode where will I receive those transaction notification? Does the client knows how to filter them for watched addresses too?

**Comment by cloudhead** [comment]
There's a flag in `protocol::Config` but it's not hooked up. Before making any changes to the code I'd suggest playing around with a fork of nakamoto to see what kind of traffic you get.

> If I make the client in relay mode where will I receive those transaction notification? Does the client knows how to filter them for watched addresses too?

No this isn't hooked up, we need to add a handler for the message type, but it's not complicated.

**Comment by rajarshimaitra** [comment]
We are moving ahead in BDK without non wallet mempool transactions.. Closing this issue on that note..

**Comment by cloudhead** [comment]
> We are moving ahead in BDK without non wallet mempool transactions.. Closing this issue on that note..

Ok, I think that's the right call, there really is no reliable way to do this without talking to a server.
